version: '2'

services:
  replicator:
    container_name: replicator
    build: .
    command: "bash -c 'iex -S mix'" # Start the server if no other command is specified
    dns:
      - 10.128.0.101
      - 10.128.0.102
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    links:
      - postgres

  postgres:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=replicator_repo
